### PR TITLE
Integrate Vaadin.Router into the app

### PR DESCRIPTION
**Pull request by web-padawan**
Related to vaadin/vaadin-router#175

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/15)

### CODE REVIEW

**Review by vlukashov — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/15)* status: 0 of 14 files reviewed, 3 unresolved discussions (waiting on @web-padawan)

___
*[app/templates/src/app/vaadin-elements-app.js, line 108 at r1](https://reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/15#-LGyqBAPEwnKB6xU8gJv:-LGyqBAPEwnKB6xU8gJw:b-u7u1uo) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/3235873f47fb8901f7be830cd7c0d432f7990cb1/app/templates/src/app/vaadin-elements-app.js#L108)):*
> ```JavaScript
> 
>     window.addEventListener(
>       'vaadin-router-location-changed',
> ```

Have you considered using the parent layouts feature to highlight the active link? Which approach do we want to promote in the starter?
___
*[app/templates/src/app/vaadin-elements-app.js, line 112 at r1](https://reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/15#-LGynX5W-2gN7whuMgTa:-LGynX5W-2gN7whuMgTb:b-fhy1jq) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/3235873f47fb8901f7be830cd7c0d432f7990cb1/app/templates/src/app/vaadin-elements-app.js#L112)):*
> ```
> import('../routes/config.js').then
> ```

A lazy import of all router code and configuration seems to slow down the app start. Yes, it improves the time to render the app shell, but since the router config bundle starts to load only after the app shell is loaded, parsed and rendered, it delays the content render for quite a while. Is this something we want to promote as a good practice?



Adding `<link rel="preload" href="./src/routes/config.js" as="script">` to index.html just above `<script type="module" src="./src/app/vaadin-elements-app.js"></script>` seems to help for the `es6-bundled` build.


However, for the `esm-bundled` build that makes things worse because in that case `routes/config.js` is loaded twice: once as a preloaded script, and the second time as a dynamic module import.

What do you think of removing lazy loading in this case at all?
___
*[app/templates/src/routes/config.js, line 26 at r1](https://reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/15#-LGynJIVCGXI3HTGW-B5:-LGynJIVCGXI3HTGW-B6:bsm8wi) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/3235873f47fb8901f7be830cd7c0d432f7990cb1/app/templates/src/routes/config.js#L26)):*
> ```
> (.*)+
> ```
Is the `+` sign intended here? Should not it be `(.*)`?

**Review by web-padawan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/15)* status: 0 of 14 files reviewed, 3 unresolved discussions (waiting on @vlukashov and @web-padawan)

___
*[app/templates/src/routes/config.js, line 26 at r1](https://reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/15#-LGynJIVCGXI3HTGW-B5:-LGztoaLD65sxOtVTsMF:b-896fix) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/3235873f47fb8901f7be830cd7c0d432f7990cb1/app/templates/src/routes/config.js#L26)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

> ```
> (.*)+
> ```
Is the `+` sign intended here? Should not it be `(.*)`?
</blockquote></details>

Done.

**Review by vlukashov — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/15)* status: 0 of 14 files reviewed, 2 unresolved discussions (waiting on @web-padawan)

___
*[app/templates/src/app/vaadin-elements-app.js, line 112 at r1](https://reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/15#-LGynX5W-2gN7whuMgTa:-LH1_n6oC5SxURXrakXu:b-hpshn1) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/3235873f47fb8901f7be830cd7c0d432f7990cb1/app/templates/src/app/vaadin-elements-app.js#L112)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

> ```
> import('../routes/config.js').then
> ```

A lazy import of all router code and configuration seems to slow down the app start. Yes, it improves the time to render the app shell, but since the router config bundle starts to load only after the app shell is loaded, parsed and rendered, it delays the content render for quite a while. Is this something we want to promote as a good practice?



Adding `<link rel="preload" href="./src/routes/config.js" as="script">` to index.html just above `<script type="module" src="./src/app/vaadin-elements-app.js"></script>` seems to help for the `es6-bundled` build.


However, for the `esm-bundled` build that makes things worse because in that case `routes/config.js` is loaded twice: once as a preloaded script, and the second time as a dynamic module import.

What do you think of removing lazy loading in this case at all?
</blockquote></details>

Here is a PR that addresses this issue: https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/pull/16

**Review by vlukashov — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/15)* status: 0 of 14 files reviewed, 4 unresolved discussions (waiting on @web-padawan)

___
*[app/templates/src/app/vaadin-elements-app.js, line 108 at r1](https://reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/15#-LGyqBAPEwnKB6xU8gJv:-LH2GB307osjvqDM2YJy:b-nboviy) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/3235873f47fb8901f7be830cd7c0d432f7990cb1/app/templates/src/app/vaadin-elements-app.js#L108)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

Have you considered using the parent layouts feature to highlight the active link? Which approach do we want to promote in the starter?
</blockquote></details>

I've tried out the parent layout approach and it does not seem to have any less code or better performane.
___
*[app/templates/src/app/vaadin-elements-app.js, line 14 at r2](https://reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/15#-LH2GlfxDWJCf0eMeSUh:-LH2GlfxDWJCf0eMeSUi:behfa25) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/e91040f1a934fcabad25186e3ffe92efc861df1b/app/templates/src/app/vaadin-elements-app.js#L14)):*
> ```JavaScript
> import '@vaadin/vaadin-lumo-styles/icons.js';
> import '../styles/shared-styles.js';
> import { EMPLOYEE_LIST, NEW_EMPLOYEE } from '../routes/pages';
> ```

It is not immediately obvious that `EMPLOYEE_LIST` and `NEW_EMPLOYEE` are simple string constants, not actual pages. How about renaming the `pages.js` file into `urls.js`: https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/pull/18
___
*[app/templates/src/app/vaadin-elements-app.js, line 113 at r2](https://reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/15#-LH2Gaw5EXeqskcs2-cA:-LH2Gaw5EXeqskcs2-cB:b-cygv00) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/e91040f1a934fcabad25186e3ffe92efc861df1b/app/templates/src/app/vaadin-elements-app.js#L113)):*
> ```
> const setupRouter = config.default;
> ```
This line can be made more readable: https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/pull/17

**Review by vlukashov — COMMENTED** [review]
> Reviewed 13 of 14 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/15)* status: all files reviewed, 5 unresolved discussions (waiting on @web-padawan)

___
*[app/templates/polymer.json, line 5 at r2](https://reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/15#-LH2H8cj3nUm-z2-dhtt:-LH2H8cj3nUm-z2-dhtu:b73q5vv) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/e91040f1a934fcabad25186e3ffe92efc861df1b/app/templates/polymer.json#L5)):*
> ```JSON
>   "root": ".",
>   "entrypoint": "index.html",
>   "shell": "src/app/<%= elementName %>.js",
> ```

Why is this file moved? Does that make the `vaadin-elemens-app` starter more closely aligned to some other existing examples?
I would subjectively prefer to keep the file at `src/app-element-name.js`.

**Review by vlukashov — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/15)* status: 9 of 14 files reviewed, 1 unresolved discussion (waiting on @vlukashov and @web-padawan)

___
*[app/templates/src/app/vaadin-elements-app.js, line 112 at r1](https://reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/15#-LGynX5W-2gN7whuMgTa:-LHXnMJP1qZL1HTmcB-l:bfsqxie) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/3235873f47fb8901f7be830cd7c0d432f7990cb1/app/templates/src/app/vaadin-elements-app.js#L112)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

Here is a PR that addresses this issue: https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/pull/16
</blockquote></details>

Done in #16
___
*[app/templates/src/app/vaadin-elements-app.js, line 14 at r2](https://reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/15#-LH2GlfxDWJCf0eMeSUh:-LHXnHGL3wOllV2cRz1s:bfsqxig) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/e91040f1a934fcabad25186e3ffe92efc861df1b/app/templates/src/app/vaadin-elements-app.js#L14)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

It is not immediately obvious that `EMPLOYEE_LIST` and `NEW_EMPLOYEE` are simple string constants, not actual pages. How about renaming the `pages.js` file into `urls.js`: https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/pull/18
</blockquote></details>

Done in #18
___
*[app/templates/src/app/vaadin-elements-app.js, line 113 at r2](https://reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/15#-LH2Gaw5EXeqskcs2-cA:-LHXnNefBh4aG3jFZ51I:bfsqxif) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/e91040f1a934fcabad25186e3ffe92efc861df1b/app/templates/src/app/vaadin-elements-app.js#L113)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

> ```
> const setupRouter = config.default;
> ```
This line can be made more readable: https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/pull/17
</blockquote></details>

Done in #17

**Review by web-padawan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/15)* status: 9 of 14 files reviewed, 1 unresolved discussion (waiting on @vlukashov and @web-padawan)

___
*[app/templates/polymer.json, line 5 at r2](https://reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/15#-LH2H8cj3nUm-z2-dhtt:-LHqPAuhDEV1aJbhnbkH:bm8ecmg) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/e91040f1a934fcabad25186e3ffe92efc861df1b/app/templates/polymer.json#L5)):*
<details><summary><i>Previously, vlukashov (Viktor Lukashov) wrote…</i></summary><blockquote>

Why is this file moved? Does that make the `vaadin-elemens-app` starter more closely aligned to some other existing examples?
I would subjectively prefer to keep the file at `src/app-element-name.js`.
</blockquote></details>

The "app" directory is sort of personal preference, some users might want to also place tests for the app component there. I'm not opposing to keeping the file as it is though

BTW, one more reason is that `vscode-icons` extension uses nice icons for folders like "src", "app", "routes", "styles", "views" etc, which helps a bit when structuring a project

**Review by vlukashov — APPROVED** [review]
> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/15)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by web-padawan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/15)* status: 7 of 14 files reviewed, 1 unresolved discussion (waiting on @vlukashov)

*[a discussion](https://reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/15#-LQ32Sa5Ai-uL-cznwDl:-LQ32Sa5Ai-uL-cznwDm:b-vq4h7e) (no related file):*
Rebased on top of the `p3-preview` branch which is now using `@vaadin/core` 12.0.0-alpha5
Also, updated the `@vaadin/router` dependency to 1.1.0

Note: the commits by @vlukashov are re-applied, as I have force pushed by accident. Sorry about that.

This should be now ready to merge.

---

**Review by pekam — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/15#-:-LQ3CNjL30sFc6_HqCAy:bnfp4nl)* status: 7 of 14 files reviewed, 1 unresolved discussion (waiting on @vlukashov)

**Review by vlukashov — APPROVED** [review]
> Reviewed 2 of 7 files at r4, 5 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/15)* status: all files reviewed, 1 unresolved discussion

**Pull request merged**
