### PR TITLE
Make employees list fill all the available space

### PR DESCRIPTION
**Pull request by manolo**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/2)

### CODE REVIEW

**Comment by tehapo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_[app/templates/src/employee-list.html, line 6 at r1](https://reviewable.io:443/reviews/vaadin/generator-polymer-init-vaadin-elements-app/2#-KRbjY7osCGyu0uKtLwl:-KRbjY7osCGyu0uKtLwm:bfz1m96) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/fb8424d0da4da93c4d4220a6111917d868d97c3e/app/templates/src/employee-list.html#L6)):_

> ``` HTML
> <link rel="import" href="../bower_components/vaadin-combo-box/vaadin-combo-box.html">
> <link rel="import" href="../bower_components/vaadin-grid/vaadin-grid.html">
> <link rel="import" href="../bower_components/paper-styles/paper-styles-classes.html">
> ```

For some reason the `paper-styles-classes` imports a deprecated file from `iron-flex-layout` and therefore outputs a deprecation warning into the console.

I would replace this with explicitly importing `iron-flex-layout` as follows:
`<link rel="import" href="../bower_components/iron-flex-layout/iron-flex-layout-classes.html">`

This also requires explicit inclusion in the `style` tag inside the `template`.
`<style include="iron-flex iron-positioning">`

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/generator-polymer-init-vaadin-elements-app/2)_

**Comment by tehapo** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/generator-polymer-init-vaadin-elements-app/2)_

**Comment by manolo** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_[app/templates/src/employee-list.html, line 6 at r1](https://reviewable.io:443/reviews/vaadin/generator-polymer-init-vaadin-elements-app/2#-KRbjY7osCGyu0uKtLwl:-KRc6jtMNX-KUNk4cG9a:b-896fix) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/fb8424d0da4da93c4d4220a6111917d868d97c3e/app/templates/src/employee-list.html#L6)):_
<details><summary>

<i>Previously, tehapo (Teemu Pöntelin) wrote…</i></summary>



> For some reason the `paper-styles-classes` imports a deprecated file from `iron-flex-layout` and therefore outputs a deprecation warning into the console.
> 
> I would replace this with explicitly importing `iron-flex-layout` as follows:
> `<link rel="import" href="../bower_components/iron-flex-layout/iron-flex-layout-classes.html">`
> 
> This also requires explicit inclusion in the `style` tag inside the `template`.
> `<style include="iron-flex iron-positioning">`
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/generator-polymer-init-vaadin-elements-app/2)_

**Comment by tehapo** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/generator-polymer-init-vaadin-elements-app/2#-:-KRc79b9wR-_8VI-eQEJ:bnfp4nl)_

**Pull request merged**
