### PR TITLE
Lumo

### LINKED ISSUE #5: Update the template for newest majors
- Upgrade element majors to target the "Lumo" versions
- Update the screenshot
- Make sure the usage instructions & tests still work
- Improve the app template with new elements
- Drop dependencies to `iron-flex-layout`, `paper-icon-button`, `paper-material`...

### PR DESCRIPTION
**Pull request by samiheikki**
Fixes #5

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/6)

### CODE REVIEW

**Comment by web-padawan** [comment]
Reviewed 30 of 30 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[app/templates/bower.json, line 21 at r1](https://reviewable.io:443/reviews/vaadin/generator-polymer-init-vaadin-elements-app/6#-L3WqP1_hCrVqcfHuIBW:-L3WqP1_hCrVqcfHuIBX:b8ikob6) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/c3fad6bbfcb43007a656f80a9144e37657364e43/app/templates/bower.json#L21)):*
> ```JSON
>     "iron-form": "PolymerElements/iron-form#^2.0.0",
>     "vaadin-core": "vaadin/vaadin-core#10.0.0-alpha14",
>     "vaadin-lumo-styles": "vaadin/vaadin-lumo-styles#1.0.0-alpha3"
> ```

BTW this also needs to be added to the `resolutions` section because of `vaadin-core` having `vaadin-lumo-styles` pinned to `alpha2`.

---

*[app/templates/bower.json, line 24 at r1](https://reviewable.io:443/reviews/vaadin/generator-polymer-init-vaadin-elements-app/6#-L3Wr63hsLB9QdHiYNVK:-L3Wr63hsLB9QdHiYNVL:b-7707su) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/c3fad6bbfcb43007a656f80a9144e37657364e43/app/templates/bower.json#L24)):*
> ```JSON
>   },
>   "resolutions": {
>     "polymer": "^2.0.0"
> ```

BTW this resolution can probably be removed, I don't see any conflicting version here

---

*[app/templates/src/employee-list.html, line 28 at r1](https://reviewable.io:443/reviews/vaadin/generator-polymer-init-vaadin-elements-app/6#-L3WsThVb3rAmTDVt_dR:-L3WsThVb3rAmTDVt_dS:b-z8xveq) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/c3fad6bbfcb43007a656f80a9144e37657364e43/app/templates/src/employee-list.html#L28)):*
> ```HTML
>     <div class="card">
>       <vaadin-vertical-layout>
>         <vaadin-text-field placeholder="Search" value="{{_filterValue}}"></vaadin-text-field>
> ```

BTW can we just use `vaadin-grid-filter` and drop this text field?

Re-implementing filtering logic brings some unwanted complexity, as we now have a `employee-new` view where text-field is demonstrated (as well as combo-box and other controls).

Getting rid of the text-field would allow us to drop vertical-layout and corresponding styles here but it is still demonstrated on the `employee-new` view.

---

*[app/templates/src/employee-list.html, line 80 at r1](https://reviewable.io:443/reviews/vaadin/generator-polymer-init-vaadin-elements-app/6#-L3UWjNCdTef67Zcgo2J:-L3UWjNDt6qDXQqgkJ5l:b-e68fv8) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/c3fad6bbfcb43007a656f80a9144e37657364e43/app/templates/src/employee-list.html#L80)):*
> ```HTML
>             return (value.toLowerCase()).indexOf(filterValue.toLowerCase()) > -1;
>           };
>           
> ```

nit: trailing whitespaces

---

*[app/templates/src/employee-new.html, line 50 at r1](https://reviewable.io:443/reviews/vaadin/generator-polymer-init-vaadin-elements-app/6#-L3UWp7A8xv9rCZPlOR6:-L3UWp7A8xv9rCZPlOR7:bntla3w) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/c3fad6bbfcb43007a656f80a9144e37657364e43/app/templates/src/employee-new.html#L50)):*
> ```HTML
>                 </vaadin-dropdown-menu>
>               </vaadin-form-item>
>   
> ```

nit: trailing whitespaces here and below

---

*[app/templates/src/shared-styles.html, line 11 at r1](https://reviewable.io:443/reviews/vaadin/generator-polymer-init-vaadin-elements-app/6#-L3UWx9gFcj-OgTcnpld:-L3UWx9hW5lZPkpkwMvC:b1p6pi6) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/c3fad6bbfcb43007a656f80a9144e37657364e43/app/templates/src/shared-styles.html#L11)):*
> ```HTML
> 
> <dom-module id="shared-styles">
>   <template include="shared-styles">
> ```

 it is the `template`, so please remove this `include="shared-styles"`

---

*[app/templates/src/vaadin-elements-app.html, line 17 at r1](https://reviewable.io:443/reviews/vaadin/generator-polymer-init-vaadin-elements-app/6#-L3UXIllvZsj4MkQFoZw:-L3UXIllvZsj4MkQFoZx:bd726i3) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/c3fad6bbfcb43007a656f80a9144e37657364e43/app/templates/src/vaadin-elements-app.html#L17)):*
> ```HTML
> <link rel="import" href="shared-styles.html">
> 
> <link rel="lazy-import" href="employee-list.html">
> ```

I'm wondering if the `lazy-import` link should have a `group` attribute here? Those are also expected to be placed inside of the `dom-module` but outside of `template`. Even if the only purpose here is to make analyzer happy, consider following the guide in the [readme](https://github.com/Polymer/lazy-imports).

---

*[app/templates/src/vaadin-elements-app.html, line 73 at r1](https://reviewable.io:443/reviews/vaadin/generator-polymer-init-vaadin-elements-app/6#-L3Uay_xxgN-OpmqZH1E:-L3Uay_xxgN-OpmqZH1F:beoy3yg) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/c3fad6bbfcb43007a656f80a9144e37657364e43/app/templates/src/vaadin-elements-app.html#L73)):*
> ```HTML
>           <a name="employee-list" href="/employee-list">Employee list</a>
>           <a name="employee-sales" href="/employee-sales">Employee sales</a>
>           <a name="employee-new" href="/employee-new">New employee</a>
> ```

BTW we can use `vaadin-list-box` or `vaadin-tabs` with vertical orientation here. Not a blocker

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/generator-polymer-init-vaadin-elements-app/6)*

**Comment by samiheikki** [comment]
Review status: 24 of 29 files reviewed at latest revision, 8 unresolved discussions.

---

*[app/templates/bower.json, line 21 at r1](https://reviewable.io:443/reviews/vaadin/generator-polymer-init-vaadin-elements-app/6#-L3WqP1_hCrVqcfHuIBW:-L3YW9xs0P2nhPjTUUrc:b-896fix) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/c3fad6bbfcb43007a656f80a9144e37657364e43/app/templates/bower.json#L21)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

BTW this also needs to be added to the `resolutions` section because of `vaadin-core` having `vaadin-lumo-styles` pinned to `alpha2`.
</blockquote></details>

Done.

---

*[app/templates/bower.json, line 24 at r1](https://reviewable.io:443/reviews/vaadin/generator-polymer-init-vaadin-elements-app/6#-L3Wr63hsLB9QdHiYNVK:-L3YWBQORYl1kPbT3rY5:b-896fix) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/c3fad6bbfcb43007a656f80a9144e37657364e43/app/templates/bower.json#L24)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

BTW this resolution can probably be removed, I don't see any conflicting version here
</blockquote></details>

Done.

---

*[app/templates/src/employee-list.html, line 28 at r1](https://reviewable.io:443/reviews/vaadin/generator-polymer-init-vaadin-elements-app/6#-L3WsThVb3rAmTDVt_dR:-L3YaFwXWPhdXSQ9rRd6:b-896fix) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/c3fad6bbfcb43007a656f80a9144e37657364e43/app/templates/src/employee-list.html#L28)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

BTW can we just use `vaadin-grid-filter` and drop this text field?

Re-implementing filtering logic brings some unwanted complexity, as we now have a `employee-new` view where text-field is demonstrated (as well as combo-box and other controls).

Getting rid of the text-field would allow us to drop vertical-layout and corresponding styles here but it is still demonstrated on the `employee-new` view.
</blockquote></details>

Done.

---

*[app/templates/src/employee-list.html, line 80 at r1](https://reviewable.io:443/reviews/vaadin/generator-polymer-init-vaadin-elements-app/6#-L3UWjNCdTef67Zcgo2J:-L3YbAxfy_rBPm8sg_zS:b-896fix) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/c3fad6bbfcb43007a656f80a9144e37657364e43/app/templates/src/employee-list.html#L80)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

nit: trailing whitespaces
</blockquote></details>

Done.

---

*[app/templates/src/employee-new.html, line 50 at r1](https://reviewable.io:443/reviews/vaadin/generator-polymer-init-vaadin-elements-app/6#-L3UWp7A8xv9rCZPlOR6:-L3YbXd1t70higQNWIQe:b-896fix) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/c3fad6bbfcb43007a656f80a9144e37657364e43/app/templates/src/employee-new.html#L50)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

nit: trailing whitespaces here and below
</blockquote></details>

Done.

---

*[app/templates/src/shared-styles.html, line 11 at r1](https://reviewable.io:443/reviews/vaadin/generator-polymer-init-vaadin-elements-app/6#-L3UWx9gFcj-OgTcnpld:-L3Yj4ZLFin_AdV9oq7P:b-896fix) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/c3fad6bbfcb43007a656f80a9144e37657364e43/app/templates/src/shared-styles.html#L11)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

 it is the `template`, so please remove this `include="shared-styles"`
</blockquote></details>

Done.

---

*[app/templates/src/vaadin-elements-app.html, line 17 at r1](https://reviewable.io:443/reviews/vaadin/generator-polymer-init-vaadin-elements-app/6#-L3UXIllvZsj4MkQFoZw:-L3Ym8HtLjMW0CMf7oCl:b4a9xrm) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/c3fad6bbfcb43007a656f80a9144e37657364e43/app/templates/src/vaadin-elements-app.html#L17)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

I'm wondering if the `lazy-import` link should have a `group` attribute here? Those are also expected to be placed inside of the `dom-module` but outside of `template`. Even if the only purpose here is to make analyzer happy, consider following the guide in the [readme](https://github.com/Polymer/lazy-imports).
</blockquote></details>

Isn't that use case more for upgrading the element itself? I'd recommend using the same style as in the polymer-starter-kit to which developers have gotten used to: https://github.com/PolymerElements/polymer-starter-kit/blob/master/src/my-app.html#L25

---

*[app/templates/src/vaadin-elements-app.html, line 73 at r1](https://reviewable.io:443/reviews/vaadin/generator-polymer-init-vaadin-elements-app/6#-L3Uay_xxgN-OpmqZH1E:-L3YofE9vaV2uoAPQkHx:b-j6nqp0) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/c3fad6bbfcb43007a656f80a9144e37657364e43/app/templates/src/vaadin-elements-app.html#L73)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

BTW we can use `vaadin-list-box` or `vaadin-tabs` with vertical orientation here. Not a blocker
</blockquote></details>

Would be cool to use, but apparently neither of those have `attr-for-selected` attribute and without the attribute it would be quite a hack. Or do you have an idea? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/generator-polymer-init-vaadin-elements-app/6)*

**Comment by tomivirkki** [comment]
Nice app! :+1: 

---

Review status: 24 of 29 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[app/templates/bower.json, line 24 at r2](https://reviewable.io:443/reviews/vaadin/generator-polymer-init-vaadin-elements-app/6#-L3m4zM_b6MshWTsOL-w:-L3m4zM_b6MshWTsOL-x:b-vt8f9g) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/f3e1248c9881176364e77d50fd822f75d9e5f511/app/templates/bower.json#L24)):*
> ```JSON
>   },
>   "resolutions": {
>     "vaadin-lumo-styles": "vaadin/vaadin-lumo-styles#1.0.0-alpha3"
> ```

Wonder why I still get a version clash on bower install

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/generator-polymer-init-vaadin-elements-app/6#-:-L3m59VaWK8LeB6dXBwO:bdvy884)*

**Comment by samiheikki** [comment]
Review status: 24 of 29 files reviewed at latest revision, 6 unresolved discussions.

---

*[app/templates/bower.json, line 24 at r2](https://reviewable.io:443/reviews/vaadin/generator-polymer-init-vaadin-elements-app/6#-L3m4zM_b6MshWTsOL-w:-L3vUdu4pm2njkuYq8oZ:bql6urd) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/f3e1248c9881176364e77d50fd822f75d9e5f511/app/templates/bower.json#L24)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Wonder why I still get a version clash on bower install
</blockquote></details>

Should be fixed now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/generator-polymer-init-vaadin-elements-app/6)*

**Comment by web-padawan** [comment]
Reviewed 4 of 5 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[app/templates/src/vaadin-elements-app.html, line 17 at r1](https://reviewable.io:443/reviews/vaadin/generator-polymer-init-vaadin-elements-app/6#-L3UXIllvZsj4MkQFoZw:-L44tHbcp5UKsMeTnuK9:b-9eqoka) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/c3fad6bbfcb43007a656f80a9144e37657364e43/app/templates/src/vaadin-elements-app.html#L17)):*
<details><summary><i>Previously, samiheikki (Sami Suo-Heikki) wrote…</i></summary><blockquote>

Isn't that use case more for upgrading the element itself? I'd recommend using the same style as in the polymer-starter-kit to which developers have gotten used to: https://github.com/PolymerElements/polymer-starter-kit/blob/master/src/my-app.html#L25
</blockquote></details>

Ok, let's keep it this way then.

---

*[app/templates/src/vaadin-elements-app.html, line 73 at r1](https://reviewable.io:443/reviews/vaadin/generator-polymer-init-vaadin-elements-app/6#-L3Uay_xxgN-OpmqZH1E:-L44u64zShQgU2qdQGSD:b3l0vwc) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/c3fad6bbfcb43007a656f80a9144e37657364e43/app/templates/src/vaadin-elements-app.html#L73)):*
<details><summary><i>Previously, samiheikki (Sami Suo-Heikki) wrote…</i></summary><blockquote>

Would be cool to use, but apparently neither of those have `attr-for-selected` attribute and without the attribute it would be quite a hack. Or do you have an idea? 
</blockquote></details>

I agree, the attribute would be better than writing additional logic in JS. We can skip it for now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/generator-polymer-init-vaadin-elements-app/6)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 25 of 30 files at r1, 4 of 5 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/generator-polymer-init-vaadin-elements-app/6#-:-L4BLp-o9PQKl5y-ISv3:bnfp4nl)*

**Comment by web-padawan** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/generator-polymer-init-vaadin-elements-app/6#-:-L4BMpvEZZHaCSR9Skwu:bnfp4nl)*

**Comment by samiheikki** [comment]
🎉

**Pull request merged**
