### PR TITLE
Remove vaadin-charts and use vaadin-core

### LINKED ISSUE #10: Remove Charts from the starter

### PR DESCRIPTION
**Pull request by samiheikki**
Fixes #10

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/11)

### CODE REVIEW

**Comment by web-padawan** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/templates/bower.json, line 19 at r1](https://reviewable.io:443/reviews/vaadin/generator-polymer-init-vaadin-elements-app/11#-L6_ZTgE5NW9fjHhVHkb:-L6_ZTgE5NW9fjHhVHkc:b-bo2dtj) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/1ac4572e59d747ce5a26c6954c993bdd25d3daf3/app/templates/bower.json#L19)):*
> ```JSON
>     "iron-selector": "PolymerElements/iron-selector#^2.0.0",
>     "iron-form": "PolymerElements/iron-form#^2.0.0",
>     "vaadin-core": "vaadin/vaadin-core#10.0.0-alpha21"
> ```

do we want to use `vaadin-core` here? seems unrelated to the scope of the PR

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/generator-polymer-init-vaadin-elements-app/11)*

**Comment by samiheikki** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/templates/bower.json, line 19 at r1](https://reviewable.io:443/reviews/vaadin/generator-polymer-init-vaadin-elements-app/11#-L6_ZTgE5NW9fjHhVHkb:-L6bAM_UlikW4zjQ1OEU:bwdrtcx) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/1ac4572e59d747ce5a26c6954c993bdd25d3daf3/app/templates/bower.json#L19)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

do we want to use `vaadin-core` here? seems unrelated to the scope of the PR
</blockquote></details>

Easy fix to do related with this: https://github.com/vaadin/expense-manager-demo/issues/84

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/generator-polymer-init-vaadin-elements-app/11)*

**Comment by tomivirkki** [comment]
Updated vaadin-core dependency to a version with the hotfixed grid

---







*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/11#-:-L78fqO-4aa8DCSA_AFA:begeh8e)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 8 of 9 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/11#-:-L78fx7mCPNAlMt41AGR:bnfp4nl)*

**Comment by web-padawan** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/templates/bower.json, line 19 at r1](https://reviewable.io:443/reviews/vaadin/generator-polymer-init-vaadin-elements-app/11#-L6_ZTgE5NW9fjHhVHkb:-L78hs4KqAtm3TSx1gPs:bb4uo0m) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/1ac4572e59d747ce5a26c6954c993bdd25d3daf3/app/templates/bower.json#L19)):*
<details><summary><i>Previously, samiheikki (Sami Suo-Heikki) wrote…</i></summary><blockquote>

Easy fix to do related with this: https://github.com/vaadin/expense-manager-demo/issues/84
</blockquote></details>

OK let's go ahead with this change for now, we can always revisit it later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/generator-polymer-init-vaadin-elements-app/11#-:-L78i6mr6hGUAFQ-5MCz:bnfp4nl)*

**Pull request merged**
