### PR TITLE
Basic conversion to P3

### LINKED ISSUE #12: Add a separate starter for Polymer 3

### PR DESCRIPTION
**Pull request by yuriy-fix**
Fixes #12

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/13)

### CODE REVIEW

**Comment by web-padawan** [comment]
Reviewed 20 of 22 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[app/templates/polymer.json, line 6 at r1](https://beta.reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/13#-L9jTW_f7jXBffUvbUtz:-L9jTW_f7jXBffUvbUu-:bqngt37) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/0374fe7c471d2c2ed62beacfd9077147cfbbcc91/app/templates/polymer.json#L6)):*
> ```JSON
>   "entrypoint": "index.html",
>   "shell": "src/<%= elementName %>.html",
>   "fragments": [],
> ```

the fragments should include the references to the lazy-loaded files. Also the shell should be updated to point to the  .js file instead of .html
```
  "shell": "src/p3-dev-app.js",
  "fragments": [
    "src/employee-list.js",
    "src/employee-new.js"
  ],
```

---

*[app/templates/polymer.json, line 10 at r1](https://beta.reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/13#-L9jWjox7emjFZ4WdR29:-L9jWjox7emjFZ4WdR2A:bmbi44z) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/2f6bab152bfc72b152ce48593035fe897dec0f77/app/templates/polymer.json#L10)):*
> ```JSON
>   ],
>   "extraDependencies": [
>     "manifest.json",
> ```

please restore this line

---

*[app/templates/polymer.json, line 12 at r1](https://beta.reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/13#-L9jWpw-BT8Ezj4mvcOw:-L9jWpw-BT8Ezj4mvcOx:b-a5cxir) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/2f6bab152bfc72b152ce48593035fe897dec0f77/app/templates/polymer.json#L12)):*
> ```JSON
>     "manifest.json",
>     "bower_components/webcomponentsjs/*.js",
>     "!bower_components/webcomponentsjs/gulpfile.js",
> ```

this line should be also preserved and modified for node_modules

---

*[app/templates/polymer.json, line 13 at r1](https://beta.reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/13#-L9jWfiY4ziM929MsIjJ:-L9jWfiY4ziM929MsIjK:bz2jc4u) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/2f6bab152bfc72b152ce48593035fe897dec0f77/app/templates/polymer.json#L13)):*
> ```JSON
>     "bower_components/webcomponentsjs/*.js",
>     "!bower_components/webcomponentsjs/gulpfile.js",
>     "employees.json"
> ```

please restore this line also, needs for bundled version to work

---

*[app/templates/sw-precache-config.js, line 3 at r1](https://beta.reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/13#-L9jUJFHBxAUOXZwGo0K:-L9jUJFHBxAUOXZwGo0L:bcokrqm) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/0374fe7c471d2c2ed62beacfd9077147cfbbcc91/app/templates/sw-precache-config.js#L3)):*
> ```JavaScript
> module.exports = {
>   staticFileGlobs: [
>     'node_modules/webcomponentsjs/webcomponents-loader.js',
> ```

need to add the `scope here

---

*[app/templates/src/404.js, line 1 at r1](https://beta.reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/13#-L9jUVdzAxsYQfjqFe3z:-L9jUVdzAxsYQfjqFe4-:b-45iwcz) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/0374fe7c471d2c2ed62beacfd9077147cfbbcc91/app/templates/src/404.js#L1)):*
> ```JavaScript
> import { PolymerElement } from '../node_modules/@polymer/polymer/polymer-element.js';
> ```

should use bare module specifiers here and below (html-tag)

---

*[app/templates/src/shared-styles.js, line 1 at r1](https://beta.reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/13#-L9jVkKq41cGpOGr9nwV:-L9jVkKq41cGpOGr9nwW:bizrzj0) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/0374fe7c471d2c2ed62beacfd9077147cfbbcc91/app/templates/src/shared-styles.js#L1)):*
> ```JavaScript
> import '../node_modules/@polymer/polymer/polymer-element.js';
> ```

should use bare module specifiers

---

*[app/templates/src/vaadin-elements-app.js, line 135 at r1](https://beta.reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/13#-L9jVpgQ2TAESH_nmcKy:-L9jVpgQ2TAESH_nmcKz:b1ccb7g) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/0374fe7c471d2c2ed62beacfd9077147cfbbcc91/app/templates/src/vaadin-elements-app.js#L135)):*
> ```JavaScript
>   _pageChanged(page) {
>     // Load page import on demand. Show 404 page if fails
>     import('./' + page + '.js').then((LazyElement) => {
> ```

this causes the following warning during build:
```
    import('./' + page + '.js').then((LazyElement) => {
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~

file:///Users/sergey/vaadin/p3-dev/src/p3-dev-app.js(132,5) warning [non-literal-import] - Cannot analyze dynamic imports with non-literal arguments
```

So it makes sense to use the `

---

*[app/templates/src/vaadin-elements-app.js, line 162 at r1](https://beta.reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/13#-L9j_Jzb7OeiiI0I5Us5:-L9j_Jzb7OeiiI0I5Us6:b8jvnnz) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/0374fe7c471d2c2ed62beacfd9077147cfbbcc91/app/templates/src/vaadin-elements-app.js#L162)):*
> ```JavaScript
>     }
> 
>     loaded.then(
> ```

I would suggest changing this to more usual syntax:
```
loaded.catch(() => this._showPage404.bind(this));
```

Per [MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch), the `

---

*[app/templates/src/employee-list.js, line 1 at r1](https://beta.reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/13#-L9jU_g-C7IbOn1pQSaF:-L9jU_g-C7IbOn1pQSaG:b8k7m50) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/0374fe7c471d2c2ed62beacfd9077147cfbbcc91/app/templates/src/employee-list.js#L1)):*
> ```JavaScript
> import { PolymerElement } from '../node_modules/@polymer/polymer/polymer-element.js';
> ```

should use bare module specifiers here and below (iron-ajax etc)

---

*[app/templates/src/employee-list.js, line 24 at r1](https://beta.reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/13#-L9jWT4w09djrrdxfvRS:-L9jWT4w09djrrdxfvRT:b-8yh4lr) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/0374fe7c471d2c2ed62beacfd9077147cfbbcc91/app/templates/src/employee-list.js#L24)):*
> ```JavaScript
>     </style>
> 
>     <iron-ajax auto="" url="employees.json" handle-as="json" last-response="{{_employees}}"></iron-ajax>
> ```

looks like the `url` needs to be 

---

*[app/templates/src/employee-list.js, line 31 at r1](https://beta.reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/13#-L9jUd_C5_LwLdg9Bm0G:-L9jUd_C5_LwLdg9Bm0H:b-dewysm) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/0374fe7c471d2c2ed62beacfd9077147cfbbcc91/app/templates/src/employee-list.js#L31)):*
> ```JavaScript
>           <template class="header">
>             <vaadin-grid-filter aria-label="First Name" path="firstName" value="[[_filterFirstName]]">
>               <vaadin-text-field slot="filter" placeholder="First Name" value="{{_filterFirstName}}" focus-target=""></vaadin-text-field>
> ```

looks like a leftover from the modulizer, those can be removed

---

*[app/templates/src/employee-new.js, line 1 at r1](https://beta.reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/13#-L9jUonQ3cEEkpGKgm6-:-L9jUonQ3cEEkpGKgm60:b-f97u8s) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/0374fe7c471d2c2ed62beacfd9077147cfbbcc91/app/templates/src/employee-new.js#L1)):*
> ```JavaScript
> import { PolymerElement } from '../node_modules/@polymer/polymer/polymer-element.js';
> ```

should use bare module specifiers here and below 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/13)*

**Comment by yuriy-fix** [comment]
Review status: 14 of 18 files reviewed at latest revision, 13 unresolved discussions.

---

*[app/templates/polymer.json, line 6 at r1](https://beta.reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/13#-L9jTW_f7jXBffUvbUtz:-L9ncxek786vmIm51cXz:b-896fix) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/0374fe7c471d2c2ed62beacfd9077147cfbbcc91/app/templates/polymer.json#L6)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

the fragments should include the references to the lazy-loaded files. Also the shell should be updated to point to the  .js file instead of .html
```
  "shell": "src/p3-dev-app.js",
  "fragments": [
    "src/employee-list.js",
    "src/employee-new.js"
  ],
```
</blockquote></details>

Done.

---

*[app/templates/polymer.json, line 10 at r1](https://beta.reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/13#-L9jWjox7emjFZ4WdR29:-L9ncw897KD5NJnP9wuj:b-896fix) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/2f6bab152bfc72b152ce48593035fe897dec0f77/app/templates/polymer.json#L10)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

please restore this line
</blockquote></details>

Done.

---

*[app/templates/polymer.json, line 12 at r1](https://beta.reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/13#-L9jWpw-BT8Ezj4mvcOw:-L9ncwgw9EPRkuMRZhNN:b-896fix) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/2f6bab152bfc72b152ce48593035fe897dec0f77/app/templates/polymer.json#L12)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

this line should be also preserved and modified for node_modules
</blockquote></details>

Done.

---

*[app/templates/polymer.json, line 13 at r1](https://beta.reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/13#-L9jWfiY4ziM929MsIjJ:-L9ncx8f1nl7tfBoLGEn:b-896fix) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/2f6bab152bfc72b152ce48593035fe897dec0f77/app/templates/polymer.json#L13)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

please restore this line also, needs for bundled version to work
</blockquote></details>

Done.

---

*[app/templates/sw-precache-config.js, line 3 at r1](https://beta.reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/13#-L9jUJFHBxAUOXZwGo0K:-L9ncvbE34f60YA-qhAx:b-896fix) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/0374fe7c471d2c2ed62beacfd9077147cfbbcc91/app/templates/sw-precache-config.js#L3)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

need to add the `scope here
</blockquote></details>

Done.

---

*[app/templates/src/vaadin-elements-app.js, line 135 at r1](https://beta.reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/13#-L9jVpgQ2TAESH_nmcKy:-L9ncsfp-1uCnNHIvkc6:b-896fix) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/0374fe7c471d2c2ed62beacfd9077147cfbbcc91/app/templates/src/vaadin-elements-app.js#L135)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

this causes the following warning during build:
```
    import('./' + page + '.js').then((LazyElement) => {
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~

file:///Users/sergey/vaadin/p3-dev/src/p3-dev-app.js(132,5) warning [non-literal-import] - Cannot analyze dynamic imports with non-literal arguments
```

So it makes sense to use the `
</blockquote></details>

Done.

---

*[app/templates/src/vaadin-elements-app.js, line 162 at r1](https://beta.reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/13#-L9j_Jzb7OeiiI0I5Us5:-L9nctB9-yVqy_N6-JSD:b-896fix) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/0374fe7c471d2c2ed62beacfd9077147cfbbcc91/app/templates/src/vaadin-elements-app.js#L162)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

I would suggest changing this to more usual syntax:
```
loaded.catch(() => this._showPage404.bind(this));
```

Per [MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch), the `
</blockquote></details>

Done.

---

*[app/templates/src/employee-list.js, line 24 at r1](https://beta.reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/13#-L9jWT4w09djrrdxfvRS:-L9ncmx0DNoK_BM1UKnO:b-a46wqy) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/0374fe7c471d2c2ed62beacfd9077147cfbbcc91/app/templates/src/employee-list.js#L24)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

looks like the `url` needs to be 
</blockquote></details>

No need to update as polymer.json was updated.

---

*[app/templates/src/employee-list.js, line 31 at r1](https://beta.reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/13#-L9jUd_C5_LwLdg9Bm0G:-L9ncqJ8-_WpL0tfPfnZ:b-896fix) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/0374fe7c471d2c2ed62beacfd9077147cfbbcc91/app/templates/src/employee-list.js#L31)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

looks like a leftover from the modulizer, those can be removed
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/13)*

**Comment by web-padawan** [comment]
Reviewed 4 of 5 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[app/templates/src/employee-list.js, line 24 at r1](https://beta.reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/13#-L9jWT4w09djrrdxfvRS:-L9ncieZ41oGnJ653tuy:b5xvcb) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/0374fe7c471d2c2ed62beacfd9077147cfbbcc91/app/templates/src/employee-list.js#L24)):*
<details><summary><i>Previously, YuriyVaadin (Yuriy Yevstihnyeyev) wrote…</i></summary><blockquote>

No need to update as polymer.json was updated.
</blockquote></details>

OK should work without rootPath (unless we want to deploy from subfolder). Should be checked on master branch first.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/13)*

**Comment by web-padawan** [comment]
Reviewed 4 of 6 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[app/templates/src/shared-styles.js, line 1 at r1](https://beta.reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/13#-L9jVkKq41cGpOGr9nwV:-L9nkD0373CjBTG4lENC:b-896fix) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/0374fe7c471d2c2ed62beacfd9077147cfbbcc91/app/templates/src/shared-styles.js#L1)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

should use bare module specifiers
</blockquote></details>

Done.

---

*[app/templates/src/employee-list.js, line 1 at r1](https://beta.reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/13#-L9jU_g-C7IbOn1pQSaF:-L9nk6j2EKeFvmkbACKv:b-896fix) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/0374fe7c471d2c2ed62beacfd9077147cfbbcc91/app/templates/src/employee-list.js#L1)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

should use bare module specifiers here and below (iron-ajax etc)
</blockquote></details>

Done.

---

*[app/templates/src/employee-new.js, line 1 at r1](https://beta.reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/13#-L9jUonQ3cEEkpGKgm6-:-L9nk9poCSIK3asyWQp9:b-896fix) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/0374fe7c471d2c2ed62beacfd9077147cfbbcc91/app/templates/src/employee-new.js#L1)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

should use bare module specifiers here and below 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/13)*

**Comment by yuriy-fix** [comment]
Review status: 14 of 20 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/templates/src/404.js, line 1 at r1](https://beta.reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/13#-L9jUVdzAxsYQfjqFe3z:-L9nvdBS7ykbLEZXnkdo:b-896fix) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/0374fe7c471d2c2ed62beacfd9077147cfbbcc91/app/templates/src/404.js#L1)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

should use bare module specifiers here and below (html-tag)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/13)*

**Comment by web-padawan** [comment]
Reviewed 7 of 7 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/13)*

**Comment by web-padawan** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/13#-:-L9skE0i6JiNurPnKXzh:bnfp4nl)*

**Pull request merged**
