### PR TITLE
First implementation

### PR DESCRIPTION
**Pull request by platosha**
Closes vaadin/components-team-tasks#190

---

This change is [Reviewable](https://reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/1)

### CODE REVIEW

**Comment by Saulis** [comment]
Reviewed 17 of 31 files at r1.
Review status: 17 of 31 files reviewed at latest revision, 8 unresolved discussions.

---

_[README.md, line 15 [r1]](https://reviewable.io:443/reviews/vaadin/generator-polymer-init-vaadin-elements-app/1#-KQdfMxr8usqGteLXfGb:-KQdfMxr8usqGteLXfGc:bwvm04k) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/efa445fbc0ee03ebd335a1b936d1bad17ab85ba8/README.md#L15)):_

> polymer init vaadin-elements-app

Tried running this from a local copy – `.gitignore` is not included in the pack and `index.js` line 60 fails.

---

_[app/index.js, line 60 [r1]](https://reviewable.io:443/reviews/vaadin/generator-polymer-init-vaadin-elements-app/1#-KQdgZNoh5KtS3udLKTk:-KQdgZNoh5KtS3udLKTl:b-fcsac5) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/efa445fbc0ee03ebd335a1b936d1bad17ab85ba8/app/index.js#L60)):_

> ``` JavaScript
>     this.fs.write(
>       this.destinationPath('.gitignore'),
>       fs.readFileSync(this.templatePath('.gitignore'))
> ```

This seemed to crash when `.gitignore` was missing

---

_[app/templates/bower.json, line 11 [r1]](https://reviewable.io:443/reviews/vaadin/generator-polymer-init-vaadin-elements-app/1#-KQdhONyVn7HuTELDNyY:-KQdhONzDZstx6aHPA87:b-7wzrwg) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/efa445fbc0ee03ebd335a1b936d1bad17ab85ba8/app/templates/bower.json#L11)):_

> ``` JSON
>   ],
>   "authors": [
>     "Vaadin Ltd"
> ```

Should the author come from the user running `init`  ?

---

_[app/templates/src/employee-list.html, line 72 [r1]](https://reviewable.io:443/reviews/vaadin/generator-polymer-init-vaadin-elements-app/1#-KQdiLHZ0QQ-KdEGUqmM:-KQdiLHZ0QQ-KdEGUqmN:b-csazpf) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/efa445fbc0ee03ebd335a1b936d1bad17ab85ba8/app/templates/src/employee-list.html#L72)):_

> ``` HTML
> 
>       observers: [
>         '_applyFilter(_filterValue, _employees.splice)'
> ```

I guess the second argument should be `_employee.splices` – although in this case I would use `_applyFilter(_filterValue, _employees)` since IMO `<iron-ajax>` never splices the array.

---

_[app/templates/src/employee-list.html, line 75 [r1]](https://reviewable.io:443/reviews/vaadin/generator-polymer-init-vaadin-elements-app/1#-KQdilIVf9XbFhGyi0Od:-KQdilIWFMIf_Yni_6f4:b-3z40io) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/efa445fbc0ee03ebd335a1b936d1bad17ab85ba8/app/templates/src/employee-list.html#L75)):_

> ``` HTML
>       ],
> 
>       _applyFilter: function() {
> ```

I would use `filterValue` and `employees` function parameters here instead of using the object properties directly. (shouldn't affect the end-result here but I personally find it a better practice)

---

_[app/templates/src/employees.json, line 2 [r1]](https://reviewable.io:443/reviews/vaadin/generator-polymer-init-vaadin-elements-app/1#-KQdjNA_gFBvAkzkqBiR:-KQdjNA_gFBvAkzkqBiS:b-nho4nx) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/efa445fbc0ee03ebd335a1b936d1bad17ab85ba8/app/templates/src/employees.json#L2)):_

> ``` JSON
> [
>   [
> ```

Argh, are these TABS I'm seeing? :smile: 

---

_[app/templates/src/vaadin-elements-app.html, line 1 [r1]](https://reviewable.io:443/reviews/vaadin/generator-polymer-init-vaadin-elements-app/1#-KQdl4zcP3KF12W5FoU4:-KQdl4zdx1v3TWl3tbZH:b-5wx9nw) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/efa445fbc0ee03ebd335a1b936d1bad17ab85ba8/app/templates/src/vaadin-elements-app.html#L1)):_

> ``` HTML
> <link rel="import" href="../bower_components/polymer/polymer.html">
> ```

Not sure if all these deps should be `../../polymer/polymer.html` – app doesn't seem to work if I open it from `http://localhost:8080/components/cli-elements/` or try opening `http://localhost:8080/components/cli-elements/test/` 

---

_[app/templates/test/index.html, line 14 [r1]](https://reviewable.io:443/reviews/vaadin/generator-polymer-init-vaadin-elements-app/1#-KQdlSqFkGCv7dz3h6Jd:-KQdlSqGa8K1L3WN3tRH:b7nmol7) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/efa445fbc0ee03ebd335a1b936d1bad17ab85ba8/app/templates/test/index.html#L14)):_

> ``` HTML
>     <script>
>       WCT.loadSuites([
>         'employee-list.html?dom=shady',
> ```

Wasn't able to verify this yet because I couldn't get the tests running manually in my browser, but I'm not sure if the GET arguments work here because the suites are opened inside an iframe. Have you guys verified that the tests are actually running in native shadow for Chrome? 

Plus, `dom` doesn't have any other type values than `shadow`, so `dom=shady` is kinda redundant.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/generator-polymer-init-vaadin-elements-app/1)_

**Comment by tomivirkki** [comment]
_[app/templates/src/employees.json, line 2 [r1]](https://reviewable.io:443/reviews/vaadin/generator-polymer-init-vaadin-elements-app/1#-KQdjNA_gFBvAkzkqBiR:-KQds6tCKdGZmpUn1mIE:bcpxy89) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/efa445fbc0ee03ebd335a1b936d1bad17ab85ba8/app/templates/src/employees.json#L2)):_
<details><summary>

<i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>



> Argh, are these TABS I'm seeing? :smile: 
> </details>
> Also, this test data is something we used in the beginning of vaadin-grid 1.0 project and have been slowly getting rid of since. Prefer the randomuser (or other) test data.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/generator-polymer-init-vaadin-elements-app/1)_

**Comment by jouni** [comment]
We have our own demo data service that we can also use. Doesnt provide
images, though, like randomuser.
pe 2. syyskuuta 2016 klo 10.50 Tomi Virkki notifications@github.com
kirjoitti:

**Comment by platosha** [comment]
Review status: 15 of 31 files reviewed at latest revision, 8 unresolved discussions.

---

_[app/templates/bower.json, line 11 [r1]](https://reviewable.io:443/reviews/vaadin/generator-polymer-init-vaadin-elements-app/1#-KQdhONyVn7HuTELDNyY:-KQeNGaMPFBGSsGTBIim:bss4a2b) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/efa445fbc0ee03ebd335a1b936d1bad17ab85ba8/app/templates/bower.json#L11)):_
<details><summary>

<i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>



> Should the author come from the user running `init`  ?
> </details>
> Removed.

---

_[app/templates/src/employee-list.html, line 72 [r1]](https://reviewable.io:443/reviews/vaadin/generator-polymer-init-vaadin-elements-app/1#-KQdiLHZ0QQ-KdEGUqmM:-KQeNMhtob8pOWpN1c7e:b-896fix) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/efa445fbc0ee03ebd335a1b936d1bad17ab85ba8/app/templates/src/employee-list.html#L72)):_
<details><summary>

<i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>



> I guess the second argument should be `_employee.splices` – although in this case I would use `_applyFilter(_filterValue, _employees)` since IMO `<iron-ajax>` never splices the array.
> </details>
> Done.

---

_[app/templates/src/employee-list.html, line 75 [r1]](https://reviewable.io:443/reviews/vaadin/generator-polymer-init-vaadin-elements-app/1#-KQdilIVf9XbFhGyi0Od:-KQeNND4dP9bjio6WR5H:b-896fix) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/efa445fbc0ee03ebd335a1b936d1bad17ab85ba8/app/templates/src/employee-list.html#L75)):_
<details><summary>

<i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>



> I would use `filterValue` and `employees` function parameters here instead of using the object properties directly. (shouldn't affect the end-result here but I personally find it a better practice)
> </details>
> Done.

---

_[app/templates/src/employees.json, line 2 [r1]](https://reviewable.io:443/reviews/vaadin/generator-polymer-init-vaadin-elements-app/1#-KQdjNA_gFBvAkzkqBiR:-KQeLZecmCcqTtFGk42V:bqdd2yi) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/efa445fbc0ee03ebd335a1b936d1bad17ab85ba8/app/templates/src/employees.json#L2)):_
<details><summary>

<i>Previously, jouni (Jouni Koivuviita) wrote…</i></summary>



> We have our own demo data service that we can also use. Doesnt provide images, though, like randomuser. pe 2. syyskuuta 2016 klo 10.50 Tomi Virkki notifications@github.com kirjoitti: 
> </details>
> Changed to a snapshot from the vaadin.com demo data service.

---

_[app/templates/src/vaadin-elements-app.html, line 1 [r1]](https://reviewable.io:443/reviews/vaadin/generator-polymer-init-vaadin-elements-app/1#-KQdl4zcP3KF12W5FoU4:-KQe8mJAqnoRtvdm72CB:b-3flwv7) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/efa445fbc0ee03ebd335a1b936d1bad17ab85ba8/app/templates/src/vaadin-elements-app.html#L1)):_
<details><summary>

<i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>



> Not sure if all these deps should be `../../polymer/polymer.html` – app doesn't seem to work if I open it from `http://localhost:8080/components/cli-elements/` or try opening `http://localhost:8080/components/cli-elements/test/` 
> </details>
> This is fine, I believe. The CLI instructs to open apps strait from the `http://localhost:8080/` root. Makes sense since it is an application, not an element.

The CLI’s application template also loads components from bower_components. Serving `/components/` requires a path mapping server configuration. Server requirements for client-side apps are no good.

---

_[app/templates/test/index.html, line 14 [r1]](https://reviewable.io:443/reviews/vaadin/generator-polymer-init-vaadin-elements-app/1#-KQdlSqFkGCv7dz3h6Jd:-KQeNf271VQ4gyypWHjc:bri16o5) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/efa445fbc0ee03ebd335a1b936d1bad17ab85ba8/app/templates/test/index.html#L14)):_
<details><summary>

<i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>



> Wasn't able to verify this yet because I couldn't get the tests running manually in my browser, but I'm not sure if the GET arguments work here because the suites are opened inside an iframe. Have you guys verified that the tests are actually running in native shadow for Chrome? 
> 
> Plus, `dom` doesn't have any other type values than `shadow`, so `dom=shady` is kinda redundant.
> </details>
> Yes, Chrome actually runs on native shadow when set, I’ve verified.

GET arguments work in iframes perfectly, becasue iframe is just another browser window with its own `location`, any valid URL works as expected there.

Both `shadow` and `shady` options are listed in the Polymer’s API docs. Although `shady` is a current default, it’s more safe to specify it explicitly here, I believe.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/generator-polymer-init-vaadin-elements-app/1)_

**Comment by platosha** [comment]
Review status: 14 of 30 files reviewed at latest revision, 8 unresolved discussions.

---

_[README.md, line 15 [r1]](https://reviewable.io:443/reviews/vaadin/generator-polymer-init-vaadin-elements-app/1#-KQdfMxr8usqGteLXfGb:-KQeSNX0lD3vvAKiBfXi:b64d867) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/efa445fbc0ee03ebd335a1b936d1bad17ab85ba8/README.md#L15)):_
<details><summary>

<i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>



> > polymer init vaadin-elements-app
> 
> Tried running this from a local copy – `.gitignore` is not included in the pack and `index.js` line 60 fails.
> 
> </details>
> Removed `.gitignore`.

---

_[app/index.js, line 60 [r1]](https://reviewable.io:443/reviews/vaadin/generator-polymer-init-vaadin-elements-app/1#-KQdgZNoh5KtS3udLKTk:-KQeSSkhMB_9F_9BXJ3E:b-896fix) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/efa445fbc0ee03ebd335a1b936d1bad17ab85ba8/app/index.js#L60)):_
<details><summary>

<i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>



> This seemed to crash when `.gitignore` was missing
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/generator-polymer-init-vaadin-elements-app/1)_

**Comment by Saulis** [comment]
:lgtm: Any thoughts on adding `vaadin-date-picker` and/or `vaadin-upload` ?

---

Reviewed 1 of 31 files at r1, 5 of 8 files at r2.
Review status: 20 of 30 files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/generator-polymer-init-vaadin-elements-app/1#-:-KQtGc3deJmsf_VZuqzO:b-llpr67)_

**Comment by platosha** [comment]
@saulis Personally I think it would be an overkill to stuff all the Elements in a single application. Two of them are enough, IMO. Otherwise it will turn into yet another Expense Manager, which is a nice demo app, but too big to be a good starting point.

---

Review status: 20 of 30 files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/generator-polymer-init-vaadin-elements-app/1#-:-KQtHFsZs0R9Q0n_HnNg:b-8ird9y)_

**Comment by tomivirkki** [comment]
:lgtm:

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/generator-polymer-init-vaadin-elements-app/1#-:-KQyRKpRqbcyG219nm_v:bnfp4nl)_

**Comment by tomivirkki** [comment]
Reviewed 23 of 31 files at r1, 7 of 8 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/generator-polymer-init-vaadin-elements-app/1)_

**Pull request merged**
