### PR TITLE
 Use vaadin-core published to npm, add time-picker, use select

### PR DESCRIPTION
**Pull request by web-padawan**
Connected to vaadin/components-team-tasks#419

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/19)

### CODE REVIEW

**Review by platosha — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/19)* status: all files reviewed, 1 unresolved discussion (waiting on @web-padawan)

___
*[app/templates/package.json, line 14 at r1](https://reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/19#-LLUbrFW9Vzvkdj0sHxt:-LLUbrFX3jPBrDn1MlTS:b-2ns86l) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/1b6a04f96a4f03897eea7716fb91a1d3fb6a9fe1/app/templates/package.json#L14)):*
> ```JSON
>     "@polymer/iron-pages": "^3.0.0-pre.19",
>     "@polymer/iron-selector": "^3.0.0-pre.19",
>     "@vaadin/vaadin-core": "^10.0.0-pre.3",
> ```

I remember we have grouped them under `@vaadin/vaadin-core` on purpose previously.

Would it make more sense to release a `@vaadin/vaadin-core` instead?

**Comment by web-padawan** [comment]
Blocked by vaadin/platform#290 so let's postpone this for now.

**Review by web-padawan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/19)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @platosha)

___
*[app/templates/package.json, line 14 at r1](https://reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/19#-LLUbrFW9Vzvkdj0sHxt:-LPBOhWp9Hz4eqFbNzUW:b-4nt9n4) ([raw file](https://github.com/vaadin/generator-polymer-init-vaadin-elements-app/blob/1b6a04f96a4f03897eea7716fb91a1d3fb6a9fe1/app/templates/package.json#L14)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

I remember we have grouped them under `@vaadin/vaadin-core` on purpose previously.

Would it make more sense to release a `@vaadin/vaadin-core` instead?
</blockquote></details>

`@vaadin/vaadin-core` is now released to npm. Updated.

**Review by platosha — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/generator-polymer-init-vaadin-elements-app/19#-:-LPytaS-7277Phz3J85m:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
